version: 2
jobs:
    build:
        docker:
            - image: byuoitav/build-env:latest

        working_directory: /go/src/github.com/byuoitav/pi-designation-microservice

        steps:
            - checkout
            - run: gvt fetch github.com/byuoitav/authmiddleware
            - run: gvt fetch github.com/go-sql-driver/mysql
            - run: gvt fetch github.com/jmoiron/sqlx
            - run: go build
