version: 2
jobs:
    build:
        docker:
            - image: byuoitav/build-env:latest

        working_directory: /go/src/github.com/byuoitav/pi-designation-microservice

        steps:
            - checkout
            - run: |
                gvt fetch github.com/byuoitav/authmiddleware
                gvt fetch github.com/go-sql-driver/mysql
                gvt fetch github.com/jmoiron/sqlx
                go build -o pi-designation.monsters
            - setup_remote_docker
            - run: |
                docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                docker build -t byuoitav/pi-designation-microservice:stage .
                docker push byuoitav/pi-designation-microservice:stage

            
