version: 2
jobs:
    build:
        docker:
            - image: byuoitav/build-env:master

        working_directory: /go/src/github.com/byuoitav/pi-designation-microservice

        steps:
            - checkout
            - run: |
                gvt fetch github.com/byuoitav/authmiddleware
                gvt fetch github.com/go-sql-driver/mysql
                gvt fetch github.com/jmoiron/sqlx
                gvt fetch github.com/byuoitav/av-api
                gvt fetch github.com/byuoitav/configuration-database-microservice
            - setup_remote_docker
            - run: make docker
            - run: ./deploy.sh $CIRCLE_PROJECT_REPONAME $CIRCLE_SHA1 stage
