version: 2
jobs:
    build:
        docker:
            - image: byuoitav/build-env:latest

        working_directory: /go/src/github.com/byuoitav/pi-designation-microservice

        steps:
            - checkout
            - run: go build
