version: 2
jobs:
    build:
        docker:
            - image: golang:1.10.0

        working_directory: /go/src/github.com/byuoitav/pi-designation-microservice

        steps:
            - run: go build
